[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production.environment]
  VITE_PRODUCTION = "true"

# Security headers (especially important for audio functionality)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://*.openrouter.ai https://*.elevenlabs.io; connect-src 'self' https://*.openrouter.ai https://*.elevenlabs.io; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data:; media-src 'self' blob: data: https://*.elevenlabs.io; object-src 'none'; base-uri 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "microphone=(), geolocation=(), camera=()" 